#!/bin/bash -e

# pyinit
#
# This script will initialize a new git project in the current folder
# create a virtalenv and configure autoenv.
#
# Please install git, virtualenv, and autoenv, activate autoenv before using this script!
# see https://pypi.python.org/pypi/autoenv for instruction on how to install and activate autoenv
#
# Check my github: https://github.com/provonet/pyinit for documentation and new releases
# Johan Bakker

function help {
  cat << EOF

USAGE: pyinit [OPTION]... python2|python3
  -d        enable debugging
  -h        show this help text and exit
  -r        remove virtualenv
  -v        show version and exit
EOF
  exit 0
}


function python_virtualenv {
  local _python=$1
  local _projectdir=$2
  local _requirement=''

  if [[ ! -d .virtualenv ]]; then
    mkdir .virtualenv
  fi

  # Create virtualenv and install requirements
  if [[ ! -d .virtualenv/${_projectdir} ]]; then
    echo -e '\e[92mcreating virtualenv\e[39m'
    virtualenv -p ${_python} .virtualenv/${_projectdir}
    if [[ -f requirements.txt ]]; then
      source .virtualenv/${_projectdir}/bin/activate
      for _requirement in requirements*.txt; do
        pip install -r ${_requirement}
      done
    fi
  fi
}


function remove_virtualenv {
  local _projectdir=$1
  local _envfile=${AUTOENV_ENV_FILENAME:-.env}
  local _authfile=${AUTOENV_AUTH_FILE:-~/.autoenv_authorized}
  echo -e '\e[92mremoving virtualenv\e[39m'
  if [[ -L .env ]]; then
    hash=($(shasum $(pwd -P)/${_envfile}))
    rm -f ${_envfile}
    if grep -q ${hash[0]} ${_authfile}; then
      cp ${_authfile} ${_authfile}.old
      set +e
      grep -v ${hash[0]} ${_authfile}.old > ${_authfile}
      set -e
    fi
  fi

  if [[ -d .virtualenv/${_projectdir} ]]; then
    rm -rf .virtualenv/${_projectdir}
    rm -d .virtualenv
  fi
}


function python_autoenv {
  local _projectdir=$1
  local _envfile=${AUTOENV_ENV_FILENAME:-.env}
  local _authfile=${AUTOENV_AUTH_FILE:-~/.autoenv_authorized}

  # Add autoenv symlink
  if [[ ! -L ${_envfile} ]]; then
    echo -e '\e[92menable autoenv\e[39m'
    touch ${_authfile}
    ln -s .virtualenv/${_projectdir}/bin/activate ${_envfile}
    hash=($(shasum $(pwd -P)/${_envfile}))
    if ! grep -q ${hash[0]} ${_authfile}; then
      echo "${hash[1]}:${hash[0]}" >> ${_authfile}
    fi
  fi
}


function gitinit {
  local _envfile=${AUTOENV_ENV_FILENAME:-.env}

  if [[ ! -f .gitignore ]]; then
    touch .gitignore
  fi

  # Add .env directory to .gitignore
  if ! grep -q "^${_envfile}$" .gitignore; then
    echo ${_envfile} >> .gitignore
  fi

  # Add .vurtualenv directory to .gitignore
  if ! grep -q '^\.virtualenv$' .gitignore; then
    echo '.virtualenv' >> .gitignore
  fi

  if [[ ! -d .git ]]; then
    echo -e '\e[92minitializing git project\e[39m'
    git init
    git add .gitignore
    git commit -m 'initial commit' .gitignore
  fi
}


# Main
PYTHON=${@: -1}
PROJECT=$(basename $PWD)
_remove=false

while getopts ":hvrd" OPTION; do
    case $OPTION in
        h)  help
            exit 1;;
        v)  echo 'pyinit 0.1.0'
            exit 0;;
        r)  _remove=true;;
        d)  set -x;;
        \?) exit 1;;
    esac
done

echo -e '\e[96mpyinit:\e[39m'
if [[ "${_remove}" == "true" ]]; then
  remove_virtualenv ${PROJECT}
  exit 0
fi

if [[ -z "${PYTHON}" ]]; then
  help
  exit 1
fi

if [[ ! ${PYTHON} =~ ^python[23]$ ]]; then
  echo -e "\e[91minvalid python version! use python2 or python3\e[39m"
  exit 1
fi

if ! which virtualenv >/dev/null; then
  echo -e '\e[91mplease install "virtualenv" before using this script!\e[39m'
  help
  exit 1
fi

if ! which shasum >/dev/null; then
  echo -e '\e[91mplease install "shasum" before using this script!\e[39m'
  help
  exit 1
fi

python_virtualenv ${PYTHON} ${PROJECT}
python_autoenv ${PROJECT}
gitinit
echo -e '\e[93muse "cd ." to enable the new virtualenv\e[39m'
